
boids:
  num: 50
  x: [-450, 50]
  y: [300, 600]
  xv: [0, 10]
  yv: [-20, 20]
  too_close_sq: 100
  matching_speed_sq: 10000
plot:
  xlim: [-500, 1500]
  ylim: [-500, 1500]
  frames: 50
  interval: 50