
boids:
  count: 50
  x_range: [-450, 50]
  y_range: [300, 600]
  xv_range: [0, 10]
  yv_range: [-20, 20]
  flock_attraction: 0.01
  avoidance_radius: 10
  formation_flying_radius: 100
  speed_matching: 0.125
plot:
  xlim: [-500, 1500]
  ylim: [-500, 1500]
  frames: 50
  interval: 50